name: auth0_web_auth
description: This package provides a Dart wrapper around the auth0-spa-js library, making the Auth0 authentication available on Flutter Web.
version: 1.0.0
repository: https://bitbucket.org/tricasthu/auth0_web_auth

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.3
  universal_html: ^2.0.8

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

platforms:
  web: